lahir = input("masukan tempat ")

hasil = len(lahir)
hasil = lahir.find("m")
hasil = lahir.rfind("a")
hasil = lahir.capitalize()
hasil = lahir.upper()
hasil = lahir.lower()
hasil = lahir.isdigit()
print(hasil)